import { PortableText } from '@portabletext/react'
import { getImageDimensions } from '@sanity/asset-utils'
import urlBuilder from '@sanity/image-url'
import type { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { createClient } from 'next-sanity'
import { useLiveQuery } from 'next-sanity/preview'
import SyntaxHighlighter from 'react-syntax-highlighter'
import { atelierDuneDark } from 'react-syntax-highlighter/dist/cjs/styles/hljs'

import Container from '~/components/Container'
import Footer from '~/components/Footer'
import { apiVersion, dataset, projectId } from '~/lib/sanity.api'
import { readToken } from '~/lib/sanity.api'
import { getClient } from '~/lib/sanity.client'
import { urlForImage } from '~/lib/sanity.image'
import {
  getPost,
  type Post,
  postBySlugQuery,
  postSlugsQuery,
} from '~/lib/sanity.queries'
import type { SharedPageProps } from '~/pages/_app'
import { formatDate } from '~/utils'

interface Query {
  [key: string]: string
}

export const getStaticProps: GetStaticProps<
  SharedPageProps & {
    post: Post
  },
  Query
> = async ({ draftMode = false, params = {} }) => {
  const client = getClient(draftMode ? { token: readToken } : undefined)
  const post = await getPost(client, params.slug)

  if (!post) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      draftMode,
      token: draftMode ? readToken : '',
      post,
    },
  }
}

export default function ProjectSlugRoute(
  props: InferGetStaticPropsType<typeof getStaticProps>,
) {
  const [post] = useLiveQuery(props.post, postBySlugQuery, {
    slug: props.post.slug.current,
  })

  const client = createClient({
    projectId,
    dataset,
    apiVersion,
    useCdn: false,
  })

  const ImageComponent = ({
    value,
    isInline,
  }: {
    value: any
    isInline: Boolean
  }) => {
    const { width, height } = getImageDimensions(value)
    return (
      <Image
        src={urlBuilder(client)
          .image(value)
          .width(isInline ? 100 : 800)
          .fit('max')
          .auto('format')
          .url()}
        alt={value.alt || ' '}
        loading="lazy"
        width={isInline ? 100 : 800}
        height={isInline ? 100 : 800}
        style={{
          // Display alongside text if image appears inside a block text span
          display: isInline ? 'inline-block' : 'block',

          // Avoid jumping around with aspect-ratio CSS property
          aspectRatio: width / height,
        }}
      />
    )
  }
  const CodeComponent = ({ value }: { value: any }) => {
    return (
      <div>
        <pre>
          <div className="flex justify-between ">
            <p className="m-0 mt-2">
              <span className="m-0 text-xl font-bold">.{value.language}</span>
            </p>
          </div>
          <SyntaxHighlighter
            language={value.language}
            style={atelierDuneDark}
            showLineNumbers
            wrapLongLines
          >
            {value.code}
          </SyntaxHighlighter>
        </pre>
      </div>
    )
  }

  const components = {
    types: {
      image: ImageComponent,
      code: CodeComponent,
      // Any other custom types you have in your content
      // Examples: mapLocation, contactForm, code, featuredProjects, latestNews, etc.
    },
  }

  return (
    <>
      <Head>
        <title>Addison.Codes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pb-16 antialiased lg:pb-24 bg-secondary dark:bg-gray-900">
        <header
          className={`bg-black w-full h-[460px] xl:h-[537px] bg-no-repeat bg-cover bg-center bg-blend-darken relative`}
        >
          {post.mainImage ? (
            <Image
              className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-80 cover"
              src={urlForImage(post.mainImage).url()}
              fill={true}
              objectFit="cover"
              alt=""
            />
          ) : (
            <Image
              className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-80 cover"
              src="https://source.unsplash.com/random/1600x600/?city,night"
              fill={true}
              objectFit="cover"
              alt=""
            />
          )}

          <div className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-80"></div>
          <div className="absolute w-full max-w-screen-xl px-4 mx-auto -translate-x-1/2 top-20 left-1/2 xl:top-1/2 xl:-translate-y-1/2 xl:px-0">
            <span className="block mb-4 text-primary">
              Published at{' '}
              <a
                href="https://addison.codes"
                className="font-semibold text-accent hover:underline"
              >
                Addison.Codes
              </a>{' '}
              on {formatDate(post._createdAt)}
            </span>
            <h1 className="max-w-4xl mb-4 text-2xl font-extrabold leading-none text-accent sm:text-3xl lg:text-4xl">
              {post.title}
            </h1>
            <p className="text-lg font-normal text-white">{post.excerpt}</p>
          </div>
        </header>
        <div className="relative z-20 flex justify-between max-w-screen-xl p-6 mx-4 bg-black rounded-lg -m-36 xl:-m-32 xl:p-9 xl:mx-auto">
          <article className="w-full text-white max-w-none format format-sm sm:format-base lg:format-lg format-blue dark:format-invert">
            <div className="pt-8 mx-auto prose prose-invert prose-slate">
              <PortableText value={post.body} components={components} />
            </div>
          </article>
          {/* <aside className="hidden xl:block" aria-labelledby="sidebar-label">
          <div className="xl:w-[336px] sticky top-6">
            <h3 id="sidebar-label" className="sr-only">
              Sidebar
            </h3>
            <div className="mb-8">
              <h4 className="mb-2 text-sm font-bold text-gray-900 uppercase dark:text-white">
                Flowbite News morning headlines
              </h4>
              <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
                Get all the stories you need-to-know from the most powerful name
                in news delivered first thing every morning to your inbox
              </p>
              <button
                type="button"
                data-modal-target="newsletter-modal"
                data-modal-toggle="newsletter-modal"
                className="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800 text-center w-full"
              >
                Subscribe
              </button>
            </div>
            <div className="mb-12">
              <h4 className="mb-4 text-sm font-bold text-gray-900 uppercase dark:text-white">
                Latest news
              </h4>
              <div className="flex items-center mb-6">
                <a href="#" className="shrink-0">
                  <img
                    src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/articles/image-1.png"
                    className="w-24 h-24 max-w-full mr-4 rounded-lg"
                    alt="Image 1"
                  />
                </a>
                <div>
                  <h5 className="mb-2 text-lg font-bold leading-tight text-gray-900 dark:text-white">
                    Our first office
                  </h5>
                  <p className="mb-2 text-gray-500 dark:text-gray-400">
                    Over the past year, Volosoft has undergone changes.
                  </p>
                  <a
                    href="#"
                    className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline"
                  >
                    Read in 9 minutes
                  </a>
                </div>
              </div>
              <div className="flex items-center mb-6">
                <a href="#" className="shrink-0">
                  <img
                    src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/articles/image-2.png"
                    className="w-24 h-24 max-w-full mr-4 rounded-lg"
                    alt="Image 2"
                  />
                </a>
                <div>
                  <h5 className="mb-2 text-lg font-bold leading-tight text-gray-900 dark:text-white">
                    Enterprise Design tips
                  </h5>
                  <p className="mb-2 text-gray-500 dark:text-gray-400">
                    Over the past year, Volosoft has undergone changes.
                  </p>
                  <a
                    href="#"
                    className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline"
                  >
                    Read in 14 minutes
                  </a>
                </div>
              </div>
              <div className="flex items-center mb-6">
                <a href="#" className="shrink-0">
                  <img
                    src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/articles/image-3.png"
                    className="w-24 h-24 max-w-full mr-4 rounded-lg"
                    alt="Image 3"
                  />
                </a>
                <div>
                  <h5 className="mb-2 text-lg font-bold leading-tight text-gray-900 dark:text-white">
                    Partnered up with Google
                  </h5>
                  <p className="mb-2 text-gray-500 dark:text-gray-400">
                    Over the past year, Volosoft has undergone changes.
                  </p>
                  <a
                    href="#"
                    className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline"
                  >
                    Read in 9 minutes
                  </a>
                </div>
              </div>
            </div>
            <div>
              <a
                href="#"
                className="flex items-center justify-center w-full h-48 mb-3 bg-gray-100 rounded-lg dark:bg-gray-700"
              >
                <svg
                  aria-hidden="true"
                  className="w-8 h-8 text-gray-400"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z"
                    clipRule="evenodd"
                  />
                </svg>
              </a>
              <p className="mb-2 text-sm text-gray-500 dark:text-gray-400">
                Students and Teachers, save up to 60% on Flowbite Creative
                Cloud.
              </p>
              <p className="text-xs text-gray-400 uppercase dark:text-gray-500">
                Ads placeholder
              </p>
            </div>
          </div>
        </aside> */}
        </div>
      </main>
      <Footer />
    </>
  )
}

export const getStaticPaths = async () => {
  const client = getClient()
  const slugs = await client.fetch(postSlugsQuery)

  return {
    paths: slugs?.map(({ slug }: { slug: Text }) => `/post/${slug}`) || [],
    fallback: 'blocking',
  }
}


